### ISSUE TITLE
Label Data Type Mismatch

### ISSUE THREAD

**Issue by Passeriform** [acheketa/cwavegan#1]
Executing train_wavegan.py over sc09 dataset returns the error:

`InvalidArgumentError: Key: label.  Data types don't match. Data type: string but expected type: float`

Full Traceback:
```
WARNING:tensorflow:From C:\Users\train\PycharmProjects\SpectrogramAnalysis\gpu\loader.py:60: batch_and_drop_remainder (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.batch(..., drop_remainder=True)`.
--------------------------------------------------------------------------------
Generator vars
[100, 16384] (1638400): G/z_project/dense/kernel:0
[16384] (16384): G/z_project/dense/bias:0
[1, 25, 512, 1024] (13107200): G/upconv_0/conv2d_transpose/kernel:0
[512] (512): G/upconv_0/conv2d_transpose/bias:0
[1, 25, 256, 512] (3276800): G/upconv_1/conv2d_transpose/kernel:0
[256] (256): G/upconv_1/conv2d_transpose/bias:0
[1, 25, 128, 256] (819200): G/upconv_2/conv2d_transpose/kernel:0
[128] (128): G/upconv_2/conv2d_transpose/bias:0
[1, 25, 64, 128] (204800): G/upconv_3/conv2d_transpose/kernel:0
[64] (64): G/upconv_3/conv2d_transpose/bias:0
[1, 25, 1, 64] (1600): G/upconv_4/conv2d_transpose/kernel:0
[1] (1): G/upconv_4/conv2d_transpose/bias:0
Total params: 19065345 (72.73 MB)
--------------------------------------------------------------------------------
Discriminator vars
[25, 1, 64] (1600): D/downconv_0/conv1d/kernel:0
[64] (64): D/downconv_0/conv1d/bias:0
[25, 64, 128] (204800): D/downconv_1/conv1d/kernel:0
[128] (128): D/downconv_1/conv1d/bias:0
[25, 128, 256] (819200): D/downconv_2/conv1d/kernel:0
[256] (256): D/downconv_2/conv1d/bias:0
[25, 256, 512] (3276800): D/downconv_3/conv1d/kernel:0
[512] (512): D/downconv_3/conv1d/bias:0
[25, 512, 1024] (13107200): D/downconv_4/conv1d/kernel:0
[1024] (1024): D/downconv_4/conv1d/bias:0
[16384, 1] (16384): D/output/dense/kernel:0
[1] (1): D/output/dense/bias:0
Total params: 17427969 (66.48 MB)
--------------------------------------------------------------------------------
2018-09-30 20:55:23.672476: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-09-30 20:55:42.424696: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1275] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label.  Data types don't match. Data type: string but expected type: float
Traceback (most recent call last):
  File "C:\Users\trainer\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
    return fn(*args)
  File "C:\Users\trainer\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\trainer\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: label.  Data types don't match. Data type: string but expected type: float
	 [[Node: ParseSingleExample/ParseSingleExample = ParseSingleExample[Tdense=[DT_FLOAT, DT_FLOAT], dense_keys=["label", "samples"], dense_shapes=[[?], [?,1]], num_sparse=0, sparse_keys=[], sparse_types=[]](arg0, ParseSingleExample/Const, ParseSingleExample/Const)]]
	 [[Node: loader/IteratorGetNext = IteratorGetNext[output_shapes=[[64,16374,1], [64,10]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](loader/OneShotIterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/trainer/PycharmProjects/SpectrogramAnalysis/gpu/train_wavegan.py", line 535, in <module>
    train(fps, args)
  File "C:/Users/trainer/PycharmProjects/SpectrogramAnalysis/gpu/train_wavegan.py", line 193, in train
    sess.run(D_train_op)
  File "C:\Users\trainer\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 583, in run
    run_metadata=run_metadata)
  File "C:\Users\trainer\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 1059, in run
    run_metadata=run_metadata)
  File "C:\Users\trainer\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 1150, in run
    raise six.reraise(*original_exc_info)
  File "F:\Apps\Python3\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\trainer\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 1135, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\trainer\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 1207, in run
    run_metadata=run_metadata)
  File "C:\Users\trainer\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 987, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\trainer\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "C:\Users\trainer\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\trainer\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)
  File "C:\Users\trainer\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: label.  Data types don't match. Data type: string but expected type: float
	 [[Node: ParseSingleExample/ParseSingleExample = ParseSingleExample[Tdense=[DT_FLOAT, DT_FLOAT], dense_keys=["label", "samples"], dense_shapes=[[?], [?,1]], num_sparse=0, sparse_keys=[], sparse_types=[]](arg0, ParseSingleExample/Const, ParseSingleExample/Const)]]
	 [[Node: loader/IteratorGetNext = IteratorGetNext[output_shapes=[[64,16374,1], [64,10]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](loader/OneShotIterator)]]

Process finished with exit code 1
```

**Comment by chaeyoung-lee** [comment]
Sorry for the late reply. I guess you already solved the problem or moved on to another.
Still, for those who might struggle with this error, I'd like to reply.

This error occurs when your tfrecord dataset is falsely produced.
- You may have not added a `--labels` flag when you called `make_tfrecord_int.py` or the file names are not in the intended format. Check whether [this part](https://github.com/acheketa/cwavegan/blob/master/data/make_tfrecord_int.py#L103-L117) of code is working properly.
- The easiest solution, if you're using sc09 dataset, is simply to download the pre-made tfrecords files. You can find the link in the readme.

Again, I'm very sorry for the late reply.
